name: Say hi on push or on pull request
run-name: ${{ github.event_name }} is trigging the workflow
on:
  pull_request:
    types: [opened]
    branches:
      - main
  issues:
    types: [opened]
jobs:
  say-hi:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hi people, I am learning github actions!"