name: Setup Node and run tests
run-name: Triggered in ${{ github.ref_name }}
on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: npm install
        run: npm ci

  run-tests:
    runs-on: ubuntu-latest 
    needs: install-dependencies
    steps:
      - uses: actions/checkout@v4

      - name: npm test
        run: npm test
    
