name: Run when commit contains "hotfix"
on: 
  pull_request:
    types: [opened, labeled]

jobs:
  normal-echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Normal run"

  if-statement:
    if: contains(github.event.pull_request.title, 'Hotfix')
    runs-on: ubuntu-latest
    steps:
      - run: echo "if statement runs!"
